# Service A Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-a-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service-a
  template:
    metadata:
      labels:
        app: service-a
    spec:
      containers:
      - name: service-a-container
        image: your-registry/service-a:latest

# Service A Service
apiVersion: v1
kind: Service
metadata:
  name: service-a-service
spec:
  selector:
    app: service-a
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080

# Repeat the above for Services B, C, D, and E with appropriate names and labels.

# Ingress Controller (for exposing API externally)
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: api-ingress
spec:
  rules:
  - host: your-api-domain.com  # Replace with your API domain
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: service-x-service  # Replace with the actual name of the service you want to expose
            port:
              number: 80
