apiVersion: v1
kind: Service
metadata:
  name: aecscomments-service
spec:
  selector:
    app: aecscomments
  ports:
    - protocol: TCP
      port: 3003  # This is the port that will be exposed on the node (Minikube VM)
      targetPort: 8080  # This is the port your container is listening on
  type: NodePort
