apiVersion: v1
kind: Service
metadata:
  name: aecspulls-service
spec:
  selector:
    app: aecspulls
  ports:
    - protocol: TCP
      port: 3001  # This is the port that will be exposed on the node (Minikube VM)
      targetPort: 8080  # This is the port your container is listening on
  type: NodePort
