
apiVersion: v1
kind: Service
metadata:
  name: aecscomments-service
spec:
  selector:
    app: aecscomments
  ports:
  - protocol: TCP
    port: 3003
    targetPort: 8080
  type: NodePort