apiVersion: v1
kind: Service
metadata:
  name: aecscontributors-service
spec:
  selector:
    app: aecscontributors
  ports:
  - protocol: TCP
    port: 3004
    targetPort: 8080
  type: NodePort