# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aecsmetrics-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aecsmetrics
  template:
    metadata:
      labels:
        app: aecsmetrics
    spec:
      containers:
      - name: aecsmetrics-container
        image: 727433422324.dkr.ecr.us-west-1.amazonaws.com/aecs:latest  # Replace with your ECR repository URI and image tag
        ports:
        - containerPort: 8080  # This is the port your application is listening on within the container
        resources:
          limits:
            cpu: "1"         # Maximum CPU limit (e.g., 1 core)
            memory: "512Mi"  # Maximum memory limit (e.g., 512 megabytes)
          requests:
            cpu: "0.5"       # Minimum CPU request (e.g., 0.5 cores)
            memory: "256Mi" 
      # imagePullSecrets:
      #   - name: 